"""initial schema: 20 таблиц маршрута

Revision ID: e18a439f9a84
Revises:
Create Date: 2026-10-03 17:17:46.611533

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e18a439f9a84"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "patient",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("anonymized_hash", sa.String(length=128), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("sex", sa.String(length=1), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sex IN ('M','F')", name="patient_sex_check"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("anonymized_hash"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "specialty",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_surgical", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "doctor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("specialty_id", sa.Integer(), nullable=True),
        sa.Column("clinic_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinic.id"],
        ),
        sa.ForeignKeyConstraint(
            ["specialty_id"],
            ["specialty.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "study",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("study_type", sa.String(length=255), nullable=False),
        sa.Column("study_date", sa.Date(), nullable=False),
        sa.Column("document_ref", sa.Text(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'received'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_study_date", "study", ["study_date"], unique=False)
    op.create_index("idx_study_type", "study", ["study_type"], unique=False)
    op.create_table(
        "trigger_def",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trigger_id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("source_study", sa.String(length=255), nullable=False),
        sa.Column("synonyms", sa.JSON(), server_default=sa.text("'[]'::jsonb"), nullable=False),
        sa.Column(
            "negative_contexts", sa.JSON(), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("thresholds", sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("specialty_id", sa.Integer(), nullable=True),
        sa.Column("potential_route", sa.Text(), nullable=True),
        sa.Column("target_sla_days", sa.Integer(), server_default=sa.text("14"), nullable=False),
        sa.Column("department", sa.String(length=255), nullable=True),
        sa.Column("priority", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("emergency_flag", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("priority BETWEEN 1 AND 4", name="trigger_def_priority_check"),
        sa.ForeignKeyConstraint(
            ["specialty_id"],
            ["specialty.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trigger_id"),
    )
    op.create_index("idx_trigger_def_specialty", "trigger_def", ["specialty_id"], unique=False)
    op.create_table(
        "finding",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("study_id", sa.UUID(), nullable=False),
        sa.Column("organ", sa.String(length=128), nullable=True),
        sa.Column("finding", sa.String(length=255), nullable=False),
        sa.Column("laterality", sa.String(length=32), nullable=True),
        sa.Column("size_mm", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("classification", sa.String(length=32), nullable=True),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=True),
        sa.Column("char_end", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("in_negative_ctx", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("source_section", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["study_id"], ["study.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_finding_name", "finding", ["finding"], unique=False)
    op.create_index("idx_finding_study", "finding", ["study_id"], unique=False)
    op.create_table(
        "mis_event",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=True),
        sa.Column("study_id", sa.UUID(), nullable=True),
        sa.Column("payload", sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("schema_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_duplicate", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["study_id"], ["study.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_mis_event_type_time", "mis_event", ["event_type", "occurred_at"], unique=False
    )
    op.create_index(
        "idx_mis_event_unprocessed",
        "mis_event",
        ["processed_at"],
        unique=False,
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    op.create_index("uq_mis_event_event_id", "mis_event", ["event_id"], unique=True)
    op.create_table(
        "protocol",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("study_id", sa.UUID(), nullable=False),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("doctor_id", sa.String(length=64), nullable=True),
        sa.Column("facts", sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("is_corrected", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_cancelled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["study_id"], ["study.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_protocol_study", "protocol", ["study_id"], unique=False)
    op.create_table(
        "trigger_match",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("protocol_id", sa.UUID(), nullable=False),
        sa.Column("trigger_def_id", sa.Integer(), nullable=False),
        sa.Column("finding_id", sa.UUID(), nullable=True),
        sa.Column("fired", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("suppressed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("suppression_reason", sa.String(length=32), nullable=True),
        sa.Column("applied_rule", sa.String(length=128), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("explanation", sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["finding_id"], ["finding.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["protocol_id"], ["protocol.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["trigger_def_id"],
            ["trigger_def.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "protocol_id", "trigger_def_id", name="uq_trigger_match_protocol_trigger"
        ),
    )
    op.create_index(
        "idx_trigger_match_fired",
        "trigger_match",
        ["fired"],
        unique=False,
        postgresql_where=sa.text("fired"),
    )
    op.create_index("idx_trigger_match_protocol", "trigger_match", ["protocol_id"], unique=False)
    op.create_table(
        "route",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("trigger_match_id", sa.UUID(), nullable=True),
        sa.Column("specialty_id", sa.Integer(), nullable=True),
        sa.Column("clinic_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "notified",
                "awaiting_booking",
                "booked",
                "visit_done",
                "decision_pending",
                "booking_required",
                "no_show",
                "referred",
                "hospitalization_scheduled",
                "hospitalized",
                "operated",
                "discharged",
                "followup_scheduled",
                "followup_done",
                "route_not_realized",
                "closed_by_patient",
                "closed_no_operation",
                "cancelled",
                name="route_status",
            ),
            server_default=sa.text("'created'"),
            nullable=False,
        ),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "close_reason",
            sa.Enum(
                "not_realized",
                "patient_refused",
                "no_operation",
                "protocol_cancelled",
                "trigger_withdrawn",
                "other",
                name="close_reason",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinic.id"],
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["specialty_id"],
            ["specialty.id"],
        ),
        sa.ForeignKeyConstraint(["trigger_match_id"], ["trigger_match.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trigger_match_id", name="uq_route_trigger_match"),
    )
    op.create_index("idx_route_patient", "route", ["patient_id"], unique=False)
    op.create_index("idx_route_status", "route", ["status"], unique=False)
    op.create_table(
        "appointment",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=True),
        sa.Column("clinic_id", sa.Integer(), nullable=True),
        sa.Column("slot_ref", sa.String(length=64), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_online", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "visit_status", sa.String(length=32), server_default=sa.text("'booked'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "visit_status IN ('booked','completed','cancelled','no_show')",
            name="appointment_visit_status_check",
        ),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinic.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctor.id"],
        ),
        sa.ForeignKeyConstraint(["route_id"], ["route.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_appointment_doctor_time", "appointment", ["doctor_id", "starts_at"], unique=False
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=True),
        sa.Column("study_id", sa.UUID(), nullable=True),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("basis", sa.Text(), nullable=True),
        sa.Column("details", sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["route_id"], ["route.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["study_id"], ["study.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_route_time", "audit_log", ["route_id", "created_at"], unique=False)
    op.create_table(
        "followup",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'scheduled'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('scheduled','confirmed','completed','missed')", name="followup_status_check"
        ),
        sa.ForeignKeyConstraint(["route_id"], ["route.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_followup_target", "followup", ["target_date"], unique=False)
    op.create_table(
        "hospitalization",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=True),
        sa.Column("actual_date", sa.Date(), nullable=True),
        sa.Column("ward", sa.String(length=64), nullable=True),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'referred'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('referred','scheduled','admitted','discharged','cancelled')",
            name="hospitalization_status_check",
        ),
        sa.ForeignKeyConstraint(["route_id"], ["route.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_hosp_route", "hospitalization", ["route_id"], unique=False)
    op.create_table(
        "notification",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(length=32), server_default=sa.text("'lk'"), nullable=False),
        sa.Column("template_code", sa.String(length=64), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "delivery_status",
            sa.String(length=32),
            server_default=sa.text("'sent'"),
            nullable=False,
        ),
        sa.Column("is_emergency", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint(
            "channel IN ('lk','push','sms','task')", name="notification_channel_check"
        ),
        sa.CheckConstraint(
            "delivery_status IN ('sent','delivered','failed','suppressed')",
            name="notification_delivery_status_check",
        ),
        sa.ForeignKeyConstraint(["route_id"], ["route.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_notification_route", "notification", ["route_id", "sent_at"], unique=False)
    op.create_table(
        "route_step",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("step_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column(
            "entered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["route_id"], ["route.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("route_id", "step_no", name="uq_route_step"),
    )
    op.create_index("idx_route_step_route", "route_step", ["route_id", "step_no"], unique=False)
    op.create_table(
        "task",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(length=64), nullable=False),
        sa.Column("assignee_role", sa.String(length=64), nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), server_default=sa.text("'open'"), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('open','in_progress','done','postponed','cancelled')",
            name="task_status_check",
        ),
        sa.ForeignKeyConstraint(["route_id"], ["route.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_task_queue", "task", ["assignee_role", "status", "due_at"], unique=False)
    op.create_table(
        "timer",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column(
            "timer_type",
            sa.Enum(
                "notify_initial",
                "notify_reminder",
                "create_task",
                "escalate",
                "close_route",
                "schedule_followup",
                name="timer_type",
            ),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fired", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("fired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("channel", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["route_id"], ["route.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("route_id", "timer_type", "due_at", name="uq_timer_route_type_due"),
    )
    op.create_index(
        "idx_timer_due", "timer", ["due_at"], unique=False, postgresql_where=sa.text("NOT fired")
    )
    op.create_index("idx_timer_route", "timer", ["route_id"], unique=False)
    op.create_table(
        "surgery",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("hospitalization_id", sa.UUID(), nullable=False),
        sa.Column("service_code", sa.String(length=64), nullable=False),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["hospitalization_id"], ["hospitalization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_surgery_performed", "surgery", ["performed_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_surgery_performed", table_name="surgery")
    op.drop_table("surgery")
    op.drop_index("idx_timer_route", table_name="timer")
    op.drop_index("idx_timer_due", table_name="timer", postgresql_where=sa.text("NOT fired"))
    op.drop_table("timer")
    op.drop_index("idx_task_queue", table_name="task")
    op.drop_table("task")
    op.drop_index("idx_route_step_route", table_name="route_step")
    op.drop_table("route_step")
    op.drop_index("idx_notification_route", table_name="notification")
    op.drop_table("notification")
    op.drop_index("idx_hosp_route", table_name="hospitalization")
    op.drop_table("hospitalization")
    op.drop_index("idx_followup_target", table_name="followup")
    op.drop_table("followup")
    op.drop_index("idx_audit_route_time", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("idx_appointment_doctor_time", table_name="appointment")
    op.drop_table("appointment")
    op.drop_index("idx_route_status", table_name="route")
    op.drop_index("idx_route_patient", table_name="route")
    op.drop_table("route")
    op.drop_index("idx_trigger_match_protocol", table_name="trigger_match")
    op.drop_index(
        "idx_trigger_match_fired", table_name="trigger_match", postgresql_where=sa.text("fired")
    )
    op.drop_table("trigger_match")
    op.drop_index("idx_protocol_study", table_name="protocol")
    op.drop_table("protocol")
    op.drop_index("uq_mis_event_event_id", table_name="mis_event")
    op.drop_index(
        "idx_mis_event_unprocessed",
        table_name="mis_event",
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    op.drop_index("idx_mis_event_type_time", table_name="mis_event")
    op.drop_table("mis_event")
    op.drop_index("idx_finding_study", table_name="finding")
    op.drop_index("idx_finding_name", table_name="finding")
    op.drop_table("finding")
    op.drop_index("idx_trigger_def_specialty", table_name="trigger_def")
    op.drop_table("trigger_def")
    op.drop_index("idx_study_type", table_name="study")
    op.drop_index("idx_study_date", table_name="study")
    op.drop_table("study")
    op.drop_table("doctor")
    op.drop_table("specialty")
    op.drop_table("patient")
    op.drop_table("clinic")
    # Alembic не удаляет PG-enum-типы при drop_table — без этого повторный
    # upgrade упадёт с DuplicateObjectError.
    for enum_name in ("route_status", "close_reason", "timer_type"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
